### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by AspirinCode** [mychem/mychem-code#16]
[Aspirin@aspirin build]$ cmake ..
-- The build type is RelWithDebInfo
-- Test module disabled
-- Using mysql-config: /usr/bin/mysql_config
-- MySQL Version: 5.7.19
-- MySQL Plugin Dir: 
-- MySQL not found.
-- Mychem installation directory: /opt/mychem/lib
-- Defining dlhandler source files
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MYSQL_LIBRARIES_mysqlclient
    linked by target "mychem-lib" in directory /home/Aspirin/Downloads/mychem-0.9.3/src
    linked by target "conversion_test" in directory /home/Aspirin/Downloads/mychem-0.9.3/tests
    linked by target "helper_test" in directory /home/Aspirin/Downloads/mychem-0.9.3/tests
    linked by target "modification_test" in directory /home/Aspirin/Downloads/mychem-0.9.3/tests
    linked by target "molmatch_test" in directory /home/Aspirin/Downloads/mychem-0.9.3/tests
    linked by target "property_test" in directory /home/Aspirin/Downloads/mychem-0.9.3/tests

-- Configuring incomplete, errors occurred!
See also "/home/Aspirin/Downloads/mychem-0.9.3/CMakeFiles/CMakeOutput.log".
CMake Error: Unable to open check cache file for write. /home/Aspirin/Downloads/mychem-0.9.3/CMakeFiles/cmake.check_cache
[Aspirin@aspirin build]$

**Comment by fredrikw** [comment]
According to the log, it can't find MySQL. Make sure that you have the development package of MySQL installed, usually called something like mysql_dev.

**Comment by AspirinCode** [comment]
[root@aspirin build]# make
Scanning dependencies of target mychem-lib
[  3%] Building C object src/CMakeFiles/mychem-lib.dir/conversion.c.o
In file included from /home/Aspirin/Downloads/mychem-0.9.3/src/conversion.h:45:0,
                 from /home/Aspirin/Downloads/mychem-0.9.3/src/conversion.c:31:
/usr/local/mysql/include/my_global.h:362:6: warning: "_WIN32" is not defined [-Wundef]
 #if (_WIN32)
      ^
/usr/local/mysql/include/my_global.h:417:6: warning: "__cplusplus" is not defined [-Wundef]
 #if (__cplusplus >= 201103L)
      ^
[  7%] Building CXX object src/CMakeFiles/mychem-lib.dir/conversion_wrapper.cpp.o
In file included from /home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:40:0:
/home/Aspirin/Downloads/mychem-0.9.3/src/fingerprints/finger2.cpp:48:21: warning: unused parameter ‘fp’ [-Wunused-parameter]
 virtual std::string DescribeBits(const std::  vector<unsigned int> fp, bool bSet=true)
                     ^
/home/Aspirin/Downloads/mychem-0.9.3/src/fingerprints/finger2.cpp:48:21: warning: unused parameter ‘bSet’ [-Wunused-parameter]
In file included from /home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:41:0:
/home/Aspirin/Downloads/mychem-0.9.3/src/fingerprints/finger3.cpp: In member function ‘virtual bool OpenBabel::PatternFP::GetFingerprint(OpenBabel::OBBase*, std::vector<unsigned int>&, int)’:
/home/Aspirin/Downloads/mychem-0.9.3/src/fingerprints/finger3.cpp:93:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     while(n < _bitcount)
               ^
/home/Aspirin/Downloads/mychem-0.9.3/src/fingerprints/finger3.cpp: In member function ‘virtual std::string OpenBabel::PatternFP::DescribeBits(std::vector<unsigned int>, bool)’:
/home/Aspirin/Downloads/mychem-0.9.3/src/fingerprints/finger3.cpp:220:36: warning: operation on ‘div’ may be undefined [-Wsequence-point]
         ngrp = (num + div -1)/div--; //rounds up
                                    ^
[ 11%] Building C object src/CMakeFiles/mychem-lib.dir/helper.c.o
In file included from /home/Aspirin/Downloads/mychem-0.9.3/src/helper.h:45:0,
                 from /home/Aspirin/Downloads/mychem-0.9.3/src/helper.c:31:
/usr/local/mysql/include/my_global.h:362:6: warning: "_WIN32" is not defined [-Wundef]
 #if (_WIN32)
      ^
/usr/local/mysql/include/my_global.h:417:6: warning: "__cplusplus" is not defined [-Wundef]
 #if (__cplusplus >= 201103L)
      ^
[ 14%] Building CXX object src/CMakeFiles/mychem-lib.dir/helper_wrapper.cpp.o
[ 18%] Building C object src/CMakeFiles/mychem-lib.dir/modification.c.o
In file included from /home/Aspirin/Downloads/mychem-0.9.3/src/modification.h:45:0,
                 from /home/Aspirin/Downloads/mychem-0.9.3/src/modification.c:31:
/usr/local/mysql/include/my_global.h:362:6: warning: "_WIN32" is not defined [-Wundef]
 #if (_WIN32)
      ^
/usr/local/mysql/include/my_global.h:417:6: warning: "__cplusplus" is not defined [-Wundef]
 #if (__cplusplus >= 201103L)
      ^
[ 22%] Building CXX object src/CMakeFiles/mychem-lib.dir/modification_wrapper.cpp.o
[ 25%] Building C object src/CMakeFiles/mychem-lib.dir/molmatch.c.o
In file included from /home/Aspirin/Downloads/mychem-0.9.3/src/molmatch.h:45:0,
                 from /home/Aspirin/Downloads/mychem-0.9.3/src/molmatch.c:31:
/usr/local/mysql/include/my_global.h:362:6: warning: "_WIN32" is not defined [-Wundef]
 #if (_WIN32)
      ^
/usr/local/mysql/include/my_global.h:417:6: warning: "__cplusplus" is not defined [-Wundef]
 #if (__cplusplus >= 201103L)
      ^
[ 29%] Building CXX object src/CMakeFiles/mychem-lib.dir/molmatch_wrapper.cpp.o
[ 33%] Building C object src/CMakeFiles/mychem-lib.dir/property.c.o
In file included from /home/Aspirin/Downloads/mychem-0.9.3/src/property.h:47:0,
                 from /home/Aspirin/Downloads/mychem-0.9.3/src/property.c:33:
/usr/local/mysql/include/my_global.h:362:6: warning: "_WIN32" is not defined [-Wundef]
 #if (_WIN32)
      ^
/usr/local/mysql/include/my_global.h:417:6: warning: "__cplusplus" is not defined [-Wundef]
 #if (__cplusplus >= 201103L)
      ^
[ 37%] Building CXX object src/CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o
In file included from /home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:41:0:
/home/Aspirin/Downloads/mychem-0.9.3/src/descriptors/groupcontrib.cpp: In member function ‘virtual double OpenBabel::OBGroupContrib::Predict(OpenBabel::OBBase*, std::string*)’:
/home/Aspirin/Downloads/mychem-0.9.3/src/descriptors/groupcontrib.cpp:160:49: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int index = 0; index < tmpmol.NumAtoms(); index++) {
                                                 ^
/home/Aspirin/Downloads/mychem-0.9.3/src/descriptors/groupcontrib.cpp: At global scope:
/home/Aspirin/Downloads/mychem-0.9.3/src/descriptors/groupcontrib.cpp:104:10: warning: unused parameter ‘param’ [-Wunused-parameter]
   double OBGroupContrib::Predict(OBBase* pOb, string* param)
          ^
[ 40%] Building CXX object src/CMakeFiles/mychem-lib.dir/serialization.cpp.o
[ 44%] Building CXX object src/CMakeFiles/mychem-lib.dir/dlhandler_unix.cpp.o
Linking CXX shared library libmychem.so
CMakeFiles/mychem-lib.dir/conversion_wrapper.cpp.o: In function `conversion':
/home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:71: undefined reference to `OpenBabel::OBConversion::SetInAndOutFormats(char const*, char const*)'
CMakeFiles/mychem-lib.dir/conversion_wrapper.cpp.o: In function `conversionV3000':
/home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:113: undefined reference to `OpenBabel::OBConversion::SetInAndOutFormats(char const*, char const*)'
CMakeFiles/mychem-lib.dir/conversion_wrapper.cpp.o: In function `V3000conversion':
/home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:156: undefined reference to `OpenBabel::OBConversion::SetInAndOutFormats(char const*, char const*)'
CMakeFiles/mychem-lib.dir/conversion_wrapper.cpp.o: In function `CMLconversion':
/home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:191: undefined reference to `OpenBabel::OBConversion::SetInAndOutFormats(char const*, char const*)'
CMakeFiles/mychem-lib.dir/conversion_wrapper.cpp.o: In function `conversionCML':
/home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:223: undefined reference to `OpenBabel::OBConversion::SetInAndOutFormats(char const*, char const*)'
CMakeFiles/mychem-lib.dir/conversion_wrapper.cpp.o:/home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:304: more undefined references to `OpenBabel::OBConversion::SetInAndOutFormats(char const*, char const*)' follow
CMakeFiles/mychem-lib.dir/conversion_wrapper.cpp.o: In function `conversionFPT':
/home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:256: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/conversion_wrapper.cpp.o: In function `serializeMolecule':
/home/Aspirin/Downloads/mychem-0.9.3/src/conversion_wrapper.cpp:335: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/modification_wrapper.cpp.o: In function `ob_add_hydrogens':
/home/Aspirin/Downloads/mychem-0.9.3/src/modification_wrapper.cpp:61: undefined reference to `OpenBabel::OBConversion::SetInAndOutFormats(char const*, char const*)'
CMakeFiles/mychem-lib.dir/modification_wrapper.cpp.o: In function `ob_remove_hydrogens':
/home/Aspirin/Downloads/mychem-0.9.3/src/modification_wrapper.cpp:91: undefined reference to `OpenBabel::OBConversion::SetInAndOutFormats(char const*, char const*)'
CMakeFiles/mychem-lib.dir/modification_wrapper.cpp.o: In function `ob_strip_salts':
/home/Aspirin/Downloads/mychem-0.9.3/src/modification_wrapper.cpp:120: undefined reference to `OpenBabel::OBConversion::SetInAndOutFormats(char const*, char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getMolWeight':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:68: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getExactMass':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:92: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getAtomCount':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:116: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getHeavyAtomCount':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:140: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getBondCount':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:164: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o:/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:188: more undefined references to `OpenBabel::OBConversion::SetInFormat(char const*)' follow
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getRotableBondCount':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:190: undefined reference to `OpenBabel::OBMol::NumRotors()'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getTotalCharge':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:212: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getFormula':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:237: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getAcceptors':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:262: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getDonors':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:292: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o: In function `getPSA':
/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:323: undefined reference to `OpenBabel::OBConversion::SetInFormat(char const*)'
CMakeFiles/mychem-lib.dir/property_wrapper.cpp.o:/home/Aspirin/Downloads/mychem-0.9.3/src/property_wrapper.cpp:351: more undefined references to `OpenBabel::OBConversion::SetInFormat(char const*)' follow
CMakeFiles/mychem-lib.dir/serialization.cpp.o: In function `unserializeOBMol(OpenBabel::OBBase*, char const*, bool)':
/home/Aspirin/Downloads/mychem-0.9.3/src/serialization.cpp:207: undefined reference to `OpenBabel::OBMol::AddAtom(OpenBabel::OBAtom&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/libmychem.so.0.9.3] Error 1
make[1]: *** [src/CMakeFiles/mychem-lib.dir/all] Error 2
make: *** [all] Error 2
[root@aspirin build]# 

have new error！！！
