### ISSUE TITLE
Assistance Request: Help installing.

### ISSUE THREAD

**Issue by mf0hka** [mychem/mychem-code#2]
I was glad to see this project migrated to github!
I am having some difficulties installing. 
http://pastebin.com/77CD60FM
it says mysql isn't isntalled... thats not right, but, I am using mariaDB front end, perhaps there is an issue there? it says pkgconfig isn't up to date. I have version 0.26 which is the stable for my Ubuntu 14.04 

-- WARNING: you are using the obsolete 'PKGCONFIG' macro, use FindPkgConfig
-- PKGCONFIG() indicates that openbabel-2.0 is not installed (install the package which contains openbabel-2.0.pc if you want to support this feature)

I do want to use openbabel. I tried looking at cmake FindPkgConfig but I failed to understand how to use it. Can you provide an example of how i might use this tool to install mychem?

openbabel version 2.3.0 is installed. 
Im going to paw through source code now, but assistance would be greatly appreciated!

**Comment by Pansanel** [comment]
The project has not been tested with MariaDB, but it is in my roadmap to support this DBMS.
Regarding your issue, are the following packages installed:
- libmysqlclient-dev
- libopenbabel-dev

**Comment by leonqli** [comment]
Any suggestion about the following errors?  Thanks in advance! 

$make test
Running tests...
Test project /home/leonqli/tools/mychem/mychem-code/build
    Start 1: ConversionTest
1/5 Test #1: ConversionTest ..................._**Failed    0.01 sec
    Start 2: HelperTest
2/5 The following tests FAILED:
      1 - ConversionTest (Failed)
      2 - HelperTest (Failed)
      3 - ModificationTest (Failed)
      4 - MolmatchTest (Failed)
      5 - PropertyTest (Failed)
Errors while running CTest
make: *_\* [test] Error 8
Test #2: HelperTest .......................**_Failed    0.00 sec
    Start 3: ModificationTest
3/5 Test #3: ModificationTest .................**_Failed    0.00 sec
    Start 4: MolmatchTest
4/5 Test #4: MolmatchTest .....................**_Failed    0.00 sec
    Start 5: PropertyTest
5/5 Test #5: PropertyTest .....................**_Failed    0.00 sec

0% tests passed, 5 tests failed out of 5

Total Test time (real) =   0.03 sec

The following tests FAILED:
      1 - ConversionTest (Failed)
      2 - HelperTest (Failed)
      3 - ModificationTest (Failed)
      4 - MolmatchTest (Failed)
      5 - PropertyTest (Failed)
Errors while running CTest
make: **\* [test] Error 8

**Comment by fredrikw** [comment]
What were your commands before running the test? Specifically, did you install the functions into mysql by running the `mysql -u user -p < src/mysqldb.sql` command?

**Comment by leonqli** [comment]
Yes. I did.  I change another computer. I got the following test results:

**Comment by leonqli** [comment]
yes. I did. I change another computer and got the following test results: 
Test project /raid/tools/mychem/mychem-code-master/build
    Start 1: ConversionTest
1/5 Test #1: ConversionTest ...................**_Failed    0.05 sec
    Start 2: HelperTest
2/5 Test #2: HelperTest .......................   Passed    0.00 sec
    Start 3: ModificationTest
3/5 Test #3: ModificationTest .................**_Failed    0.02 sec
    Start 4: MolmatchTest
4/5 Test #4: MolmatchTest .....................**_Exception: SegFault  0.12 sec
    Start 5: PropertyTest
5/5 Test #5: PropertyTest .....................**_Failed    0.06 sec

20% tests passed, 4 tests failed out of 5

Total Test time (real) =   0.26 sec

The following tests FAILED:
      1 - ConversionTest (Failed)
      3 - ModificationTest (Failed)
      4 - MolmatchTest (SEGFAULT)
      5 - PropertyTest (Failed)
Errors while running CTest
make: **\* [test] Error 8

---

This is my cmake output file: 

cmake: /opt/UCSF/Chimera64-1.10.2/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
cmake: /opt/UCSF/Chimera64-1.10.2/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
cmake: /opt/UCSF/Chimera64-1.10.2/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The build type is RelWithDebInfo
-- Test module enabled
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- WARNING: you are using the obsolete 'PKGCONFIG' macro, use FindPkgConfig
-- OPENBABEL_MINI_FOUND <TRUE>
-- Found OpenBabel2: /usr/local/lib/libopenbabel.so
-- Open Babel Exe: /usr/local/bin/babel
-- Using mysql-config: /usr/bin/mysql_config
-- MySQL Version: 5.5.47
-- MySQL Plugin Dir: /usr/lib/mysql/plugin
-- Found MySQL 5.5.47: /usr/include/mysql, /usr/lib/x86_64-linux-gnu/libmysqlclient.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so
-- Mychem installation directory: /usr/lib/mysql/plugin
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for stdio.h
-- Looking for stdio.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Defining dlhandler source files
-- Configuring done
-- Generating done
-- Build files have been written to: /raid/tools/mychem/mychem-code-master/build

**Comment by Pansanel** [comment]
Which OS are you using?
Can you post the content of  the `build/Testing/Temporary/LastTest.log` after removing the password?

**Comment by Pansanel** [comment]
No answer. I close the issue.
