### ISSUE TITLE
make mychem work with MySQL 8 (from Doker image with debian buster)

### ISSUE THREAD

**Issue by yann2084** [mychem/mychem-code#31]
Hello,
I'm trying to compile mychem source code v.1.0.x in a debian buster with MySQL 8.
To prepare compilation, i begin to install theses packages : 
`openbabel libopenbabel-dev libmysqlclient-dev python-mysqldb cmake g++ zip wget pkg-config
`
Then after wget mychem-1.0.0.zip and make build folder in mychem-1.0.0 folder and run cmake I have this following error : 
```
CMake Error: The following variables are used in this project, but they
>> are set to NOTFOUND.
>> Please set them or make sure they are set and tested correctly in the
>> CMake files:
>> MYSQL_LIBRARIES_atomic
```
Is it possible to have some help please ?

Thank a lot

**Comment by paulo-maia** [comment]
Hi yann, check #30
